/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_tbd;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Suyapa
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_menu = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jb_producto = new javax.swing.JButton();
        jb_proveedor = new javax.swing.JButton();
        jb_reporte = new javax.swing.JButton();
        jb_cliente = new javax.swing.JButton();
        jb_factura = new javax.swing.JButton();
        jb_venta = new javax.swing.JButton();
        jb_inventario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jB_empleado = new javax.swing.JButton();
        jB_user = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jd_sesion = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt_usuario = new javax.swing.JTextField();
        jt_password = new javax.swing.JPasswordField();
        jb_entrar = new javax.swing.JButton();
        jf_producto = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jT_Nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jT_Codigo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jF_Fecha = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jT_costo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jT_Descripcion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jT_precio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jT_CodigoFab = new javax.swing.JTextField();
        jB_AgregarP = new javax.swing.JButton();
        jB_ModificarP = new javax.swing.JButton();
        jB_EliminarP = new javax.swing.JButton();
        jB_TablaPro = new javax.swing.JButton();
        jf_clientes = new javax.swing.JFrame();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jT_idC = new javax.swing.JTextField();
        jT_NombreC = new javax.swing.JTextField();
        jT_apellidoC = new javax.swing.JTextField();
        jT_rtnC = new javax.swing.JTextField();
        jT_telefono = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jf_venta = new javax.swing.JFrame();
        jf_factura = new javax.swing.JFrame();
        jButton8 = new javax.swing.JButton();
        tf_fac_codigo = new javax.swing.JTextField();
        tf_fac_usuario = new javax.swing.JTextField();
        tf_fac_rtnCliente = new javax.swing.JTextField();
        tf_fac_nombreCliente = new javax.swing.JTextField();
        tf_fac_ApellidoCliente = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        tf_fac_CantidadProductos = new javax.swing.JTextField();
        tf_fac_Total = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jf_inventario = new javax.swing.JFrame();
        jB_CargarInvet = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_CargarInventario = new javax.swing.JTable();
        jf_reporte = new javax.swing.JFrame();
        jB_GenerarRep = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jf_proveedor = new javax.swing.JFrame();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jT_CodigoPr = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jT_DireccionPr = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jT_RTNPr = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jT_TelefonoPr = new javax.swing.JTextField();
        jB_TablaPr = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jT_nombrePr = new javax.swing.JTextField();
        jT_ApellidoPr = new javax.swing.JTextField();
        jD_Tabla_Productos = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jT_productos1 = new javax.swing.JTable();
        jD_TablaPr = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jD_Empleados = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        jT_idEm = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jT_NomEm = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jT_ApelidoEm = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jT_UserEm = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jT_SalarioEm = new javax.swing.JTextField();
        jB_AgregarE = new javax.swing.JButton();
        jB_Eliminar = new javax.swing.JButton();
        jD_users = new javax.swing.JDialog();
        jLabel30 = new javax.swing.JLabel();
        jT_User = new javax.swing.JTextField();
        jB_AgregarUser = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jP_passUser = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_iniciar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel4.setText("Menú");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        jb_producto.setText("Productos");
        jb_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_productoMouseClicked(evt);
            }
        });
        jPanel1.add(jb_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jb_proveedor.setText("Proveedores");
        jb_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_proveedorMouseClicked(evt);
            }
        });
        jPanel1.add(jb_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));

        jb_reporte.setText("Reportes");
        jb_reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_reporteMouseClicked(evt);
            }
        });
        jPanel1.add(jb_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 90, -1));

        jb_cliente.setText("Clientes");
        jb_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_clienteMouseClicked(evt);
            }
        });
        jPanel1.add(jb_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 93, -1));

        jb_factura.setText("Facturas");
        jb_factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_facturaMouseClicked(evt);
            }
        });
        jPanel1.add(jb_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 93, -1));

        jb_venta.setText("Ventas");
        jb_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ventaMouseClicked(evt);
            }
        });
        jPanel1.add(jb_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 81, -1));

        jb_inventario.setText("Inventarios");
        jb_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_inventarioMouseClicked(evt);
            }
        });
        jPanel1.add(jb_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_tbd/g-gif-update.gif"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jB_empleado.setText("Empleado");
        jB_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_empleadoMouseClicked(evt);
            }
        });
        jPanel1.add(jB_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 90, -1));

        jB_user.setText("User");
        jB_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_userMouseClicked(evt);
            }
        });
        jPanel1.add(jB_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 70, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_tbd/supermarket-shelf-1094815_640.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 70, -1, -1));

        javax.swing.GroupLayout jf_menuLayout = new javax.swing.GroupLayout(jf_menu.getContentPane());
        jf_menu.getContentPane().setLayout(jf_menuLayout);
        jf_menuLayout.setHorizontalGroup(
            jf_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jf_menuLayout.setVerticalGroup(
            jf_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jd_sesion.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Inicio de Sesiòn");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        jb_entrar.setText("Login");
        jb_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_entrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_sesionLayout = new javax.swing.GroupLayout(jd_sesion.getContentPane());
        jd_sesion.getContentPane().setLayout(jd_sesionLayout);
        jd_sesionLayout.setHorizontalGroup(
            jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_sesionLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_sesionLayout.createSequentialGroup()
                        .addGroup(jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_entrar)
                            .addGroup(jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jt_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(jt_password))))
                    .addComponent(jLabel1))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jd_sesionLayout.setVerticalGroup(
            jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_sesionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jb_entrar)
                .addGap(36, 36, 36))
        );

        jLabel7.setText("Nombre");

        jLabel8.setText("Codigo");

        jLabel9.setText("Fecha de Expiracion");

        jF_Fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel10.setText("Costo");

        jLabel11.setText("Descripcion");

        jLabel12.setText("precio de venta");

        jLabel13.setText("Codigo de Fabricante");

        jB_AgregarP.setText("Agregar");
        jB_AgregarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_AgregarPMouseClicked(evt);
            }
        });

        jB_ModificarP.setText("Modificar");

        jB_EliminarP.setText("Eliminar");

        jB_TablaPro.setText("Tabla Productos");
        jB_TablaPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_TablaProMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_productoLayout = new javax.swing.GroupLayout(jf_producto.getContentPane());
        jf_producto.getContentPane().setLayout(jf_productoLayout);
        jf_productoLayout.setHorizontalGroup(
            jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_productoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jf_productoLayout.createSequentialGroup()
                        .addComponent(jB_AgregarP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_ModificarP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_EliminarP))
                    .addGroup(jf_productoLayout.createSequentialGroup()
                        .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jf_productoLayout.createSequentialGroup()
                                .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT_precio)
                                    .addComponent(jT_CodigoFab)))
                            .addGroup(jf_productoLayout.createSequentialGroup()
                                .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_productoLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18))
                                    .addGroup(jf_productoLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(22, 22, 22)))
                                .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT_Codigo)
                                    .addComponent(jT_Nombre)))
                            .addGroup(jf_productoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jF_Fecha))
                            .addGroup(jf_productoLayout.createSequentialGroup()
                                .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jT_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jB_TablaPro)))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jf_productoLayout.setVerticalGroup(
            jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_productoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_productoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jT_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jf_productoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jB_TablaPro)))
                .addGap(18, 18, 18)
                .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jF_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jT_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jT_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jT_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jT_CodigoFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_AgregarP)
                    .addComponent(jB_ModificarP)
                    .addComponent(jB_EliminarP))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButton5.setText("Agregar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Eliminar");

        jLabel18.setText("ID");

        jLabel19.setText("Nombre");

        jLabel20.setText("Apellido");

        jLabel21.setText("RTN");

        jLabel22.setText("Telefono");

        jButton7.setText("Tabla");

        javax.swing.GroupLayout jf_clientesLayout = new javax.swing.GroupLayout(jf_clientes.getContentPane());
        jf_clientes.getContentPane().setLayout(jf_clientesLayout);
        jf_clientesLayout.setHorizontalGroup(
            jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_clientesLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(33, 33, 33)
                .addComponent(jButton5)
                .addGap(52, 52, 52))
            .addGroup(jf_clientesLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addGap(30, 30, 30)
                .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jT_idC)
                    .addComponent(jT_NombreC)
                    .addComponent(jT_apellidoC)
                    .addComponent(jT_rtnC)
                    .addComponent(jT_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jf_clientesLayout.setVerticalGroup(
            jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_clientesLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jT_idC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jT_NombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jT_apellidoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jT_rtnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jT_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jf_ventaLayout = new javax.swing.GroupLayout(jf_venta.getContentPane());
        jf_venta.getContentPane().setLayout(jf_ventaLayout);
        jf_ventaLayout.setHorizontalGroup(
            jf_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jf_ventaLayout.setVerticalGroup(
            jf_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jButton8.setText("Agregar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel32.setText("Código");

        jLabel33.setText("Usuario");

        jLabel34.setText("rtn Cliente");

        jLabel35.setText("Nombre Cliente");

        jLabel36.setText("Apellido Cliente");

        jLabel37.setText("Cantidad Productos");

        jLabel38.setText("Total");

        javax.swing.GroupLayout jf_facturaLayout = new javax.swing.GroupLayout(jf_factura.getContentPane());
        jf_factura.getContentPane().setLayout(jf_facturaLayout);
        jf_facturaLayout.setHorizontalGroup(
            jf_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_facturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(43, 43, 43))
            .addGroup(jf_facturaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jf_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addGap(24, 24, 24)
                .addGroup(jf_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_fac_Total, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(tf_fac_CantidadProductos)
                    .addComponent(tf_fac_codigo)
                    .addComponent(tf_fac_usuario)
                    .addComponent(tf_fac_rtnCliente)
                    .addComponent(tf_fac_nombreCliente)
                    .addComponent(tf_fac_ApellidoCliente))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jf_facturaLayout.setVerticalGroup(
            jf_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_facturaLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jf_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_fac_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(jf_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_fac_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(jf_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_fac_rtnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addGroup(jf_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_fac_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addGroup(jf_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_fac_ApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addGroup(jf_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_fac_CantidadProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addGap(18, 18, 18)
                .addGroup(jf_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_fac_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(38, 38, 38))
        );

        jB_CargarInvet.setText("Cargar Inventario");

        jT_CargarInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jT_CargarInventario);

        javax.swing.GroupLayout jf_inventarioLayout = new javax.swing.GroupLayout(jf_inventario.getContentPane());
        jf_inventario.getContentPane().setLayout(jf_inventarioLayout);
        jf_inventarioLayout.setHorizontalGroup(
            jf_inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_inventarioLayout.createSequentialGroup()
                .addGroup(jf_inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_inventarioLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jB_CargarInvet))
                    .addGroup(jf_inventarioLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jf_inventarioLayout.setVerticalGroup(
            jf_inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_inventarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jB_CargarInvet)
                .addGap(31, 31, 31))
        );

        jB_GenerarRep.setText("Generar");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout jf_reporteLayout = new javax.swing.GroupLayout(jf_reporte.getContentPane());
        jf_reporte.getContentPane().setLayout(jf_reporteLayout);
        jf_reporteLayout.setHorizontalGroup(
            jf_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_reporteLayout.createSequentialGroup()
                .addGroup(jf_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_reporteLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jB_GenerarRep))
                    .addGroup(jf_reporteLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jf_reporteLayout.setVerticalGroup(
            jf_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_reporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jB_GenerarRep)
                .addContainerGap())
        );

        jButton2.setText("Agregar ");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton4.setText("Eliminar");

        jLabel14.setText("Codigo");

        jLabel15.setText("Direccion");

        jLabel16.setText("RTN");

        jLabel17.setText("Telefono");

        jB_TablaPr.setText("Generar Tabla");
        jB_TablaPr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_TablaPrMouseClicked(evt);
            }
        });

        jLabel23.setText("Nombre");

        jLabel24.setText("Apellido");

        javax.swing.GroupLayout jf_proveedorLayout = new javax.swing.GroupLayout(jf_proveedor.getContentPane());
        jf_proveedor.getContentPane().setLayout(jf_proveedorLayout);
        jf_proveedorLayout.setHorizontalGroup(
            jf_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_proveedorLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jf_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addGap(58, 58, 58)
                .addGroup(jf_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_proveedorLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(jf_proveedorLayout.createSequentialGroup()
                        .addGroup(jf_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jT_ApellidoPr, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_nombrePr, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_CodigoPr, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_DireccionPr, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_RTNPr, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_TelefonoPr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_TablaPr)
                        .addGap(26, 26, 26))))
        );
        jf_proveedorLayout.setVerticalGroup(
            jf_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_proveedorLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jf_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jT_CodigoPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_TablaPr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jf_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jT_nombrePr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jf_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jT_ApellidoPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jf_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jT_DireccionPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jT_RTNPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jT_TelefonoPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jf_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(31, 31, 31))
        );

        jT_productos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Codigo", "Fecha de expiracion", "Costo", "Descripcion", "precio de venta", "Codigo de fabricante", "Categoria"
            }
        ));
        jScrollPane4.setViewportView(jT_productos1);

        javax.swing.GroupLayout jD_Tabla_ProductosLayout = new javax.swing.GroupLayout(jD_Tabla_Productos.getContentPane());
        jD_Tabla_Productos.getContentPane().setLayout(jD_Tabla_ProductosLayout);
        jD_Tabla_ProductosLayout.setHorizontalGroup(
            jD_Tabla_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_Tabla_ProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jD_Tabla_ProductosLayout.setVerticalGroup(
            jD_Tabla_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_Tabla_ProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jD_TablaPrLayout = new javax.swing.GroupLayout(jD_TablaPr.getContentPane());
        jD_TablaPr.getContentPane().setLayout(jD_TablaPrLayout);
        jD_TablaPrLayout.setHorizontalGroup(
            jD_TablaPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_TablaPrLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_TablaPrLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(270, 270, 270))
        );
        jD_TablaPrLayout.setVerticalGroup(
            jD_TablaPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_TablaPrLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        jLabel25.setText("id");

        jLabel26.setText("Nombre");

        jLabel27.setText("Apellido");

        jLabel28.setText("User");

        jLabel29.setText("Salario");

        jB_AgregarE.setText("Agregar");
        jB_AgregarE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_AgregarEMouseClicked(evt);
            }
        });

        jB_Eliminar.setText("Eliminar");

        javax.swing.GroupLayout jD_EmpleadosLayout = new javax.swing.GroupLayout(jD_Empleados.getContentPane());
        jD_Empleados.getContentPane().setLayout(jD_EmpleadosLayout);
        jD_EmpleadosLayout.setHorizontalGroup(
            jD_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_EmpleadosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jD_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jB_AgregarE)
                    .addGroup(jD_EmpleadosLayout.createSequentialGroup()
                        .addGroup(jD_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(32, 32, 32)
                        .addGroup(jD_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_idEm)
                            .addComponent(jT_NomEm)
                            .addComponent(jT_ApelidoEm)
                            .addComponent(jT_UserEm)
                            .addComponent(jT_SalarioEm, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_Eliminar)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jD_EmpleadosLayout.setVerticalGroup(
            jD_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_EmpleadosLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jD_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jT_idEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jD_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jT_NomEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jD_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jT_ApelidoEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jD_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jT_UserEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jD_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jT_SalarioEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jD_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_AgregarE)
                    .addComponent(jB_Eliminar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jD_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jD_usersMouseClicked(evt);
            }
        });

        jLabel30.setText("User");

        jB_AgregarUser.setText("Agregar");
        jB_AgregarUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_AgregarUserMouseClicked(evt);
            }
        });

        jLabel31.setText("Password");

        javax.swing.GroupLayout jD_usersLayout = new javax.swing.GroupLayout(jD_users.getContentPane());
        jD_users.getContentPane().setLayout(jD_usersLayout);
        jD_usersLayout.setHorizontalGroup(
            jD_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_usersLayout.createSequentialGroup()
                .addGroup(jD_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jD_usersLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_AgregarUser))
                    .addGroup(jD_usersLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jD_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)
                        .addGroup(jD_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_User, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jP_passUser))))
                .addGap(99, 99, 99))
        );
        jD_usersLayout.setVerticalGroup(
            jD_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_usersLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jD_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jT_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jD_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jP_passUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jB_AgregarUser)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");
        setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");

        mi_iniciar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        mi_iniciar.setText("Iniciar Sesión");
        mi_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_iniciarActionPerformed(evt);
            }
        });
        jMenu1.add(mi_iniciar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_iniciarActionPerformed

        jd_sesion.pack();
        jd_sesion.setModal(true);
        jd_sesion.setLocationRelativeTo(this);
        jd_sesion.setVisible(true);
    }//GEN-LAST:event_mi_iniciarActionPerformed

    private void jb_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_entrarMouseClicked
        // INICIA SESIÓN
        if (jt_usuario.getText().equals("user") && jt_password.getText().equals("1234")) {
            jd_sesion.setVisible(false);
            jf_menu.pack();
            jf_menu.setResizable(true);
            jf_menu.setLocationRelativeTo(this);
            jf_menu.setVisible(true);

            //d_sesion.setVisible(false);
            jt_usuario.setText("");
            jt_password.setText("");
        } else {
            JOptionPane.showMessageDialog(jd_sesion, "Usuario Incorrecto");
            jt_usuario.setText("");
            jt_password.setText("");
        }

    }//GEN-LAST:event_jb_entrarMouseClicked

    private void jb_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_productoMouseClicked
        //ENTRAR A PRODUCTOS
        jf_producto.pack();
        jf_producto.setResizable(true);
        jf_producto.setLocationRelativeTo(this);
        jf_producto.setVisible(true);

    }//GEN-LAST:event_jb_productoMouseClicked

    private void jb_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_clienteMouseClicked
        //ENTRAR A CLIENTES
        jf_clientes.pack();
        jf_clientes.setResizable(true);
        jf_clientes.setLocationRelativeTo(this);
        jf_clientes.setVisible(true);
    }//GEN-LAST:event_jb_clienteMouseClicked

    private void jb_ventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ventaMouseClicked
        //ENTRAR A VENTAS
        jf_venta.pack();
        jf_venta.setResizable(true);
        jf_venta.setLocationRelativeTo(this);
        jf_venta.setVisible(true);
    }//GEN-LAST:event_jb_ventaMouseClicked

    private void jb_facturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_facturaMouseClicked
        // ENTRAR A FACTURAS
        jf_factura.pack();
        jf_factura.setResizable(true);
        jf_factura.setLocationRelativeTo(this);
        jf_factura.setVisible(true);
    }//GEN-LAST:event_jb_facturaMouseClicked

    private void jb_inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_inventarioMouseClicked
        //ENTRAR A INVENTARIOS
        jf_inventario.pack();
        jf_inventario.setResizable(true);
        jf_inventario.setLocationRelativeTo(this);
        jf_inventario.setVisible(true);
    }//GEN-LAST:event_jb_inventarioMouseClicked

    private void jb_reporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_reporteMouseClicked
        // ENTRAR A REPORTES
        jf_reporte.pack();
        jf_reporte.setResizable(true);
        jf_reporte.setLocationRelativeTo(this);
        jf_reporte.setVisible(true);
    }//GEN-LAST:event_jb_reporteMouseClicked

    private void jb_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_proveedorMouseClicked
        //ENTRAR A PROVEEDORES
        jf_proveedor.pack();
        jf_proveedor.setResizable(true);
        jf_proveedor.setLocationRelativeTo(this);
        jf_proveedor.setVisible(true);
    }//GEN-LAST:event_jb_proveedorMouseClicked

    private void jB_TablaProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_TablaProMouseClicked
        // TODO add your handling code here:
        jD_Tabla_Productos.pack();
        jD_Tabla_Productos.setResizable(true);
        jD_Tabla_Productos.setLocationRelativeTo(this);
        jD_Tabla_Productos.setVisible(true);
    }//GEN-LAST:event_jB_TablaProMouseClicked

    private void jB_TablaPrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_TablaPrMouseClicked
        // TODO add your handling code here:
        jD_TablaPr.pack();
        jD_TablaPr.setResizable(true);
        jD_TablaPr.setLocationRelativeTo(this);
        jD_TablaPr.setVisible(true);
    }//GEN-LAST:event_jB_TablaPrMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        Cliente c = new Cliente();
        jT_idC.getText();
        jT_NombreC.getText();
        jT_apellidoC.getText();
        jT_rtnC.getText();
        jT_telefono.getText();
        c.setApellidoCliente(jT_apellidoC.getText());
        c.setNombreCliente(jT_NombreC.getText());
        c.setRtnCliente(Integer.parseInt(jT_rtnC.getText()));
        c.setTelefonoCliente(Integer.parseInt(jT_telefono.getText()));
        c.setIdCliente(Integer.parseInt(jT_idC.getText()));

        daoCliente dao = new daoCliente();

        if (dao.create(c)) {
            JOptionPane.showMessageDialog(this, "Se ingreso exitosamente a la base de datos");
            jT_idC.setText("");
            jT_NombreC.setText("");
            jT_apellidoC.setText("");
            jT_rtnC.setText("");
            jT_telefono.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jB_AgregarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_AgregarPMouseClicked
        // TODO add your handling code here:
        Producto p = new Producto();
        jT_Nombre.getText();
        jT_Codigo.getText();
        jF_Fecha.getText();
        jT_costo.getText();
        jT_Descripcion.getText();
        jT_precio.getText();
        jT_CodigoFab.getText();
        p.setCategoria(jT_Nombre.getText());
        p.setCodigoProducto(Integer.parseInt(jT_Codigo.getText()));
        p.setFechaExpiracion(null);
        p.setCosto(Float.parseFloat(jT_costo.getText()));
        p.setDescripcion(jT_Descripcion.getText());
        p.setPrecioVenta(Float.parseFloat(jT_precio.getText()));
        p.setCodigoProveedor(Integer.parseInt(jT_CodigoFab.getText()));
        daoProducto dao = new daoProducto();

        if (dao.create(p)) {
            JOptionPane.showMessageDialog(this, "Se ingreso exitosamente a la base de datos");

            jT_Nombre.setText("");
            jT_Codigo.setText("");
            jF_Fecha.setText("");
            jT_costo.setText("");
            jT_Descripcion.setText("");
            jT_precio.setText("");
            jT_CodigoFab.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_jB_AgregarPMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:

        Proveedor c = new Proveedor();
        jT_CodigoPr.getText();
        jT_DireccionPr.getText();
        jT_RTNPr.getText();
        jT_TelefonoPr.getText();
        jT_nombrePr.getText();
        jT_ApellidoPr.getText();

        c.setNombreProveedor(jT_nombrePr.getText());
        c.setApellidoProveedor(jT_ApellidoPr.getText());
        c.setCodigoProveedor(Integer.parseInt(jT_CodigoPr.getText()));
        c.setRtnProveedor(Integer.parseInt(jT_RTNPr.getText()));
        c.setTelefonoProveedor(Integer.parseInt(jT_TelefonoPr.getText()));
        c.setDireccionProveedor(jT_DireccionPr.getText());

        daoProveedor dao = new daoProveedor();

        if (dao.create(c)) {
            JOptionPane.showMessageDialog(this, "Se ingreso exitosamente a la base de datos");
            jT_CodigoPr.setText("");
            jT_DireccionPr.setText("");
            jT_RTNPr.setText("");
            jT_TelefonoPr.setText("");
            jT_nombrePr.setText("");
            jT_ApellidoPr.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void jB_AgregarEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_AgregarEMouseClicked
        // TODO add your handling code here:
        Empleados c = new Empleados();
        jT_idEm.getText();
        jT_NomEm.getText();
        jT_ApelidoEm.getText();
        jT_UserEm.getText();
        jT_SalarioEm.getText();

        c.setIdEmpleado(Integer.parseInt(jT_idEm.getText()));
        c.setNombreEmpleado(jT_NomEm.getText());
        c.setApellidoEmpleado(jT_ApelidoEm.getText());
        c.setUsuario(jT_UserEm.getText());
        c.setSalario(Integer.parseInt(jT_SalarioEm.getText()));

        daoEmpleado dao = new daoEmpleado();

        if (dao.create(c)) {
            JOptionPane.showMessageDialog(this, "Se ingreso exitosamente a la base de datos");
            jT_idEm.setText("");
            jT_NomEm.setText("");
            jT_ApelidoEm.setText("");
            jT_UserEm.setText("");
            jT_SalarioEm.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }


    }//GEN-LAST:event_jB_AgregarEMouseClicked

    private void jB_AgregarUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_AgregarUserMouseClicked
        // TODO add your handling code here:
        Usuario c = new Usuario();
        jT_User.getText();
        jP_passUser.getText();

        c.setUsuario(jT_User.getText());
        c.setPassword(jP_passUser.getText());

        daoUsuario dao = new daoUsuario();

        if (dao.create(c)) {
            JOptionPane.showMessageDialog(this, "Se ingreso exitosamente a la base de datos");

            jT_User.setText("");
            jP_passUser.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }

    }//GEN-LAST:event_jB_AgregarUserMouseClicked

    private void jB_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_empleadoMouseClicked
        // TODO add your handling code here:
        jD_Empleados.pack();
        jD_Empleados.setResizable(true);
        jD_Empleados.setLocationRelativeTo(this);
        jD_Empleados.setVisible(true);
    }//GEN-LAST:event_jB_empleadoMouseClicked

    private void jB_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_userMouseClicked

        jD_users.pack();
        jD_users.setResizable(true);
        jD_users.setLocationRelativeTo(this);
        jD_users.setVisible(true);

    }//GEN-LAST:event_jB_userMouseClicked

    private void jD_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jD_usersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jD_usersMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:

        /*
        
            int codigoFactura;
            String usuario;
            int rtnCliente;
            String nombreCliente;
            String apellidoCliente;
            int cantidadProductos;
            Date fecha;
            double total;
        
         */
        Factura f = new Factura();
        
                
        //La fecha se incluye automaticamente
        Calendar calendar = Calendar.getInstance();
        java.sql.Date fechaSQL = new java.sql.Date(calendar.getTime().getTime());
        
        tf_fac_codigo.getText();
        tf_fac_usuario.getText();
        tf_fac_rtnCliente.getText();
        tf_fac_nombreCliente.getText();
        tf_fac_ApellidoCliente.getText();
        tf_fac_CantidadProductos.getText();
        tf_fac_Total.getText();
        f.setCodigoFactura(Integer.parseInt(tf_fac_codigo.getText()));
        f.setApellidoCliente(tf_fac_ApellidoCliente.getText());
        f.setNombreCliente(tf_fac_nombreCliente.getText());
        f.setRtnCliente(Integer.parseInt(tf_fac_rtnCliente.getText()));
        f.setCantidadProductos(Integer.parseInt(tf_fac_CantidadProductos.getText()));
        f.setTotal(Double.parseDouble(tf_fac_Total.getText()));
        f.setFecha(fechaSQL);
       
        daoFactura dao = new daoFactura();

        if (dao.create(f)) {
            JOptionPane.showMessageDialog(this, "Se ingreso exitosamente a la base de datos");
            tf_fac_codigo.setText("");
            tf_fac_usuario.setText("");
            tf_fac_rtnCliente.setText("");
            tf_fac_nombreCliente.setText("");
            tf_fac_ApellidoCliente.setText("");
            tf_fac_Total.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_jButton8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_AgregarE;
    private javax.swing.JButton jB_AgregarP;
    private javax.swing.JButton jB_AgregarUser;
    private javax.swing.JButton jB_CargarInvet;
    private javax.swing.JButton jB_Eliminar;
    private javax.swing.JButton jB_EliminarP;
    private javax.swing.JButton jB_GenerarRep;
    private javax.swing.JButton jB_ModificarP;
    private javax.swing.JButton jB_TablaPr;
    private javax.swing.JButton jB_TablaPro;
    private javax.swing.JButton jB_empleado;
    private javax.swing.JButton jB_user;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JDialog jD_Empleados;
    private javax.swing.JDialog jD_TablaPr;
    private javax.swing.JDialog jD_Tabla_Productos;
    private javax.swing.JDialog jD_users;
    private javax.swing.JFormattedTextField jF_Fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField jP_passUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jT_ApelidoEm;
    private javax.swing.JTextField jT_ApellidoPr;
    private javax.swing.JTable jT_CargarInventario;
    private javax.swing.JTextField jT_Codigo;
    private javax.swing.JTextField jT_CodigoFab;
    private javax.swing.JTextField jT_CodigoPr;
    private javax.swing.JTextField jT_Descripcion;
    private javax.swing.JTextField jT_DireccionPr;
    private javax.swing.JTextField jT_NomEm;
    private javax.swing.JTextField jT_Nombre;
    private javax.swing.JTextField jT_NombreC;
    private javax.swing.JTextField jT_RTNPr;
    private javax.swing.JTextField jT_SalarioEm;
    private javax.swing.JTextField jT_TelefonoPr;
    private javax.swing.JTextField jT_User;
    private javax.swing.JTextField jT_UserEm;
    private javax.swing.JTextField jT_apellidoC;
    private javax.swing.JTextField jT_costo;
    private javax.swing.JTextField jT_idC;
    private javax.swing.JTextField jT_idEm;
    private javax.swing.JTextField jT_nombrePr;
    private javax.swing.JTextField jT_precio;
    private javax.swing.JTable jT_productos1;
    private javax.swing.JTextField jT_rtnC;
    private javax.swing.JTextField jT_telefono;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jb_cliente;
    private javax.swing.JButton jb_entrar;
    private javax.swing.JButton jb_factura;
    private javax.swing.JButton jb_inventario;
    private javax.swing.JButton jb_producto;
    private javax.swing.JButton jb_proveedor;
    private javax.swing.JButton jb_reporte;
    private javax.swing.JButton jb_venta;
    private javax.swing.JDialog jd_sesion;
    private javax.swing.JFrame jf_clientes;
    private javax.swing.JFrame jf_factura;
    private javax.swing.JFrame jf_inventario;
    private javax.swing.JFrame jf_menu;
    private javax.swing.JFrame jf_producto;
    private javax.swing.JFrame jf_proveedor;
    private javax.swing.JFrame jf_reporte;
    private javax.swing.JFrame jf_venta;
    private javax.swing.JPasswordField jt_password;
    private javax.swing.JTextField jt_usuario;
    private javax.swing.JMenuItem mi_iniciar;
    private javax.swing.JTextField tf_fac_ApellidoCliente;
    private javax.swing.JTextField tf_fac_CantidadProductos;
    private javax.swing.JTextField tf_fac_Total;
    private javax.swing.JTextField tf_fac_codigo;
    private javax.swing.JTextField tf_fac_nombreCliente;
    private javax.swing.JTextField tf_fac_rtnCliente;
    private javax.swing.JTextField tf_fac_usuario;
    // End of variables declaration//GEN-END:variables

}
