/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_tbd;

import javax.swing.JOptionPane;

/**
 *
 * @author Suyapa
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_menu = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jb_producto = new javax.swing.JButton();
        jb_proveedor = new javax.swing.JButton();
        jb_reporte = new javax.swing.JButton();
        jb_cliente = new javax.swing.JButton();
        jb_factura = new javax.swing.JButton();
        jb_venta = new javax.swing.JButton();
        jb_inventario = new javax.swing.JButton();
        jd_sesion = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt_usuario = new javax.swing.JTextField();
        jt_password = new javax.swing.JPasswordField();
        jb_entrar = new javax.swing.JButton();
        jf_producto = new javax.swing.JFrame();
        jf_clientes = new javax.swing.JFrame();
        jf_venta = new javax.swing.JFrame();
        jf_factura = new javax.swing.JFrame();
        jf_inventario = new javax.swing.JFrame();
        jf_reporte = new javax.swing.JFrame();
        jf_proveedor = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_iniciar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel4.setText("Menú");

        jb_producto.setText("Productos");
        jb_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_productoMouseClicked(evt);
            }
        });

        jb_proveedor.setText("Proveedores");
        jb_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_proveedorMouseClicked(evt);
            }
        });

        jb_reporte.setText("Reportes");
        jb_reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_reporteMouseClicked(evt);
            }
        });

        jb_cliente.setText("Clientes");
        jb_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_clienteMouseClicked(evt);
            }
        });

        jb_factura.setText("Facturas");
        jb_factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_facturaMouseClicked(evt);
            }
        });

        jb_venta.setText("Ventas");
        jb_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ventaMouseClicked(evt);
            }
        });

        jb_inventario.setText("Inventarios");
        jb_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_inventarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jb_inventario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jb_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_proveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_factura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jb_reporte)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_producto)
                    .addComponent(jb_cliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_factura)
                    .addComponent(jb_venta))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jb_proveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jb_inventario)))
                .addGap(18, 18, 18)
                .addComponent(jb_reporte)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jf_menuLayout = new javax.swing.GroupLayout(jf_menu.getContentPane());
        jf_menu.getContentPane().setLayout(jf_menuLayout);
        jf_menuLayout.setHorizontalGroup(
            jf_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jf_menuLayout.setVerticalGroup(
            jf_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jd_sesion.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Inicio de Sesiòn");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        jb_entrar.setText("Login");
        jb_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_entrarMouseClicked(evt);
            }
        });
        jb_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_entrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_sesionLayout = new javax.swing.GroupLayout(jd_sesion.getContentPane());
        jd_sesion.getContentPane().setLayout(jd_sesionLayout);
        jd_sesionLayout.setHorizontalGroup(
            jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_sesionLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_sesionLayout.createSequentialGroup()
                        .addGroup(jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_entrar)
                            .addGroup(jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jt_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(jt_password))))
                    .addComponent(jLabel1))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jd_sesionLayout.setVerticalGroup(
            jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_sesionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jd_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jb_entrar)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jf_productoLayout = new javax.swing.GroupLayout(jf_producto.getContentPane());
        jf_producto.getContentPane().setLayout(jf_productoLayout);
        jf_productoLayout.setHorizontalGroup(
            jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jf_productoLayout.setVerticalGroup(
            jf_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jf_clientesLayout = new javax.swing.GroupLayout(jf_clientes.getContentPane());
        jf_clientes.getContentPane().setLayout(jf_clientesLayout);
        jf_clientesLayout.setHorizontalGroup(
            jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jf_clientesLayout.setVerticalGroup(
            jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jf_ventaLayout = new javax.swing.GroupLayout(jf_venta.getContentPane());
        jf_venta.getContentPane().setLayout(jf_ventaLayout);
        jf_ventaLayout.setHorizontalGroup(
            jf_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jf_ventaLayout.setVerticalGroup(
            jf_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jf_facturaLayout = new javax.swing.GroupLayout(jf_factura.getContentPane());
        jf_factura.getContentPane().setLayout(jf_facturaLayout);
        jf_facturaLayout.setHorizontalGroup(
            jf_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jf_facturaLayout.setVerticalGroup(
            jf_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jf_inventarioLayout = new javax.swing.GroupLayout(jf_inventario.getContentPane());
        jf_inventario.getContentPane().setLayout(jf_inventarioLayout);
        jf_inventarioLayout.setHorizontalGroup(
            jf_inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jf_inventarioLayout.setVerticalGroup(
            jf_inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jf_reporteLayout = new javax.swing.GroupLayout(jf_reporte.getContentPane());
        jf_reporte.getContentPane().setLayout(jf_reporteLayout);
        jf_reporteLayout.setHorizontalGroup(
            jf_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jf_reporteLayout.setVerticalGroup(
            jf_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jf_proveedorLayout = new javax.swing.GroupLayout(jf_proveedor.getContentPane());
        jf_proveedor.getContentPane().setLayout(jf_proveedorLayout);
        jf_proveedorLayout.setHorizontalGroup(
            jf_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jf_proveedorLayout.setVerticalGroup(
            jf_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");
        setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mi_iniciar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        mi_iniciar.setText("Iniciar Sesión");
        mi_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_iniciarActionPerformed(evt);
            }
        });
        jMenu1.add(mi_iniciar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_iniciarActionPerformed
    jd_sesion.setLocationRelativeTo(this);
    jd_sesion.setVisible(true);
    jd_sesion.setResizable(true);
    }//GEN-LAST:event_mi_iniciarActionPerformed

    private void jb_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_entrarMouseClicked
        // INICIA SESIÓN

        if(jt_usuario.getText()=="user" && jt_password.getText()=="1234"){
            jf_menu.setVisible(true);
            jt_usuario.setText("");
            jt_password.setText("");
        }else{
            JOptionPane.showMessageDialog(jd_sesion, "Usuario Incorrecto");
            jt_usuario.setText("");
            jt_password.setText("");
        }
        
    }//GEN-LAST:event_jb_entrarMouseClicked

    private void jb_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_productoMouseClicked
        //ENTRAR A PRODUCTOS
        jf_producto.setVisible(true);
        
    }//GEN-LAST:event_jb_productoMouseClicked

    private void jb_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_clienteMouseClicked
        //ENTRAR A CLIENTES
        jf_clientes.setVisible(true);
    }//GEN-LAST:event_jb_clienteMouseClicked

    private void jb_ventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ventaMouseClicked
        //ENTRAR A VENTAS
        jf_venta.setVisible(true);
    }//GEN-LAST:event_jb_ventaMouseClicked

    private void jb_facturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_facturaMouseClicked
        // ENTRAR A FACTURAS
        jf_factura.setVisible(true);
    }//GEN-LAST:event_jb_facturaMouseClicked

    private void jb_inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_inventarioMouseClicked
        //ENTRAR A INVENTARIOS
        jf_inventario.setVisible(true);
    }//GEN-LAST:event_jb_inventarioMouseClicked

    private void jb_reporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_reporteMouseClicked
        // ENTRAR A REPORTES
        jf_reporte.setVisible(true);
    }//GEN-LAST:event_jb_reporteMouseClicked

    private void jb_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_proveedorMouseClicked
        //ENTRAR A PROVEEDORES
        jf_proveedor.setVisible(true);
    }//GEN-LAST:event_jb_proveedorMouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
          
        
    
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jb_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_entrarActionPerformed
       
    }//GEN-LAST:event_jb_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_cliente;
    private javax.swing.JButton jb_entrar;
    private javax.swing.JButton jb_factura;
    private javax.swing.JButton jb_inventario;
    private javax.swing.JButton jb_producto;
    private javax.swing.JButton jb_proveedor;
    private javax.swing.JButton jb_reporte;
    private javax.swing.JButton jb_venta;
    private javax.swing.JDialog jd_sesion;
    private javax.swing.JFrame jf_clientes;
    private javax.swing.JFrame jf_factura;
    private javax.swing.JFrame jf_inventario;
    private javax.swing.JFrame jf_menu;
    private javax.swing.JFrame jf_producto;
    private javax.swing.JFrame jf_proveedor;
    private javax.swing.JFrame jf_reporte;
    private javax.swing.JFrame jf_venta;
    private javax.swing.JPasswordField jt_password;
    private javax.swing.JTextField jt_usuario;
    private javax.swing.JMenuItem mi_iniciar;
    // End of variables declaration//GEN-END:variables
}
